### ISSUE TITLE
OS X 10.11.3 - "heroku" commands fail

### ISSUE THREAD

**Issue by bfollekHOD** [heroku/heroku#1897]
heroku --version and heroku apps:info consistently fail at "Installing core plugins". Logs attached.

heroku-cli: Installing core plugins (retrying)...
 ▸    Error installing package.
 ▸    npm ERR! Darwin 15.3.0
 ▸    npm ERR! argv "/Users/bobfollek/.heroku/node-v5.4.1-darwin-x64/bin/node" "/Users/bobfollek/.heroku/node-v5.4.1-darwin-x64/lib/node_modules/npm/cli.js" "install" "heroku-apps" "heroku-cli-addons" "heroku-fork" "heroku-git" "heroku-local" "heroku-run" "heroku-spaces" "heroku-status"
 ▸    npm ERR! node v5.4.1
 ▸    npm ERR! npm  v3.3.10
 ▸    npm ERR! code EPERM
 ▸    npm ERR! errno EPERM
 ▸    npm ERR! syscall connect
 ▸
 ▸    npm ERR! Error: connect EPERM 54.230.38.197:443 - Local (0.0.0.0:0)
 ▸    npm ERR!     at Object.exports._errnoException (util.js:856:11)
 ▸    npm ERR!     at exports._exceptionWithHostPort (util.js:879:20)
 ▸    npm ERR!     at connect (net.js:843:14)
 ▸    npm ERR!     at net.js:985:7
 ▸    npm ERR!     at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
 ▸    npm ERR!     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)
 ▸    npm ERR!  { [Error: connect EPERM 54.230.38.197:443 - Local (0.0.0.0:0)]
 ▸    npm ERR!   code: 'EPERM',
 ▸    npm ERR!   errno: 'EPERM',
 ▸    npm ERR!   syscall: 'connect',
 ▸    npm ERR!   address: '54.230.38.197',
 ▸    npm ERR!   port: 443 }
 ▸    npm ERR!
 ▸    npm ERR! Please try running this command again as root/Administrator.
 ▸
 ▸    npm ERR! Please include the following file with any support request:
 ▸    npm ERR!     /Users/bobfollek/.heroku/npm-debug.log
 ▸
 ▸    Try running again with GODE_DEBUG=info to see more output.
 !    error getting commands pid 51930 exit 1

[error.log.txt](https://github.com/heroku/heroku/files/129637/error.log.txt)
[npm-debug.log.txt](https://github.com/heroku/heroku/files/129639/npm-debug.log.txt)

**Comment by ransombriggs** [comment]
@bfollekHOD are you behind a proxy server?  do you have any configuration in `~/.npmrc`?

**Comment by fro** [comment]
Same here :-(
Here's my logs:

```
2016/02/15 23:36:31 Updating Heroku v4 CLI to 4.27.21-839acbb (master)... 
2016/02/15 23:36:32 done
2016/02/15 23:36:32 reexecing new CLI...
2016/02/15 23:36:32 Updating plugins... 
2016/02/15 23:36:36 done. Updated 2 packages.
2016/02/15 23:36:36 heroku-cli: Installing core plugins...
2016/02/15 23:36:42 heroku-cli: Installing core plugins (retrying)...
2016/02/15 23:36:47 
2016/02/15 23:36:47  ▸    Error reading plugin: heroku-pipelines
 ▸    exit status 1
 ▸    module.js:327
 ▸        throw err;
 ▸        ^
 ▸    
 ▸    Error: Cannot find module 'heroku-pipelines'
 ▸        at Function.Module._resolveFilename (module.js:325:15)
 ▸        at Function.Module._load (module.js:276:25)
 ▸        at Module.require (module.js:353:17)
 ▸        at require (internal/module.js:12:17)
 ▸        at [eval]:2:15
 ▸        at Object.exports.runInThisContext (vm.js:54:17)
 ▸        at Object.<anonymous> ([eval]-wrapper:6:22)
 ▸        at Module._compile (module.js:397:26)
 ▸        at node.js:611:27
 ▸        at nextTickCallbackWith0Args (node.js:452:9)
2016/02/15 23:40:05 heroku-cli: Installing core plugins...
2016/02/15 23:40:13 heroku-cli: Installing core plugins (retrying)...
2016/02/15 23:40:19 
2016/02/15 23:40:19  ▸    Error reading plugin: heroku-pipelines
 ▸    exit status 1
 ▸    module.js:327
 ▸        throw err;
 ▸        ^
 ▸    
 ▸    Error: Cannot find module 'heroku-pipelines'
 ▸        at Function.Module._resolveFilename (module.js:325:15)
 ▸        at Function.Module._load (module.js:276:25)
 ▸        at Module.require (module.js:353:17)
 ▸        at require (internal/module.js:12:17)
 ▸        at [eval]:2:15
 ▸        at Object.exports.runInThisContext (vm.js:54:17)
 ▸        at Object.<anonymous> ([eval]-wrapper:6:22)
 ▸        at Module._compile (module.js:397:26)
 ▸        at node.js:611:27
 ▸        at nextTickCallbackWith0Args (node.js:452:9)
2016/02/15 23:40:19 heroku-cli: Installing core plugins...
2016/02/15 23:40:21 heroku-cli: Installing core plugins (retrying)...
2016/02/15 23:40:26 
2016/02/15 23:40:26  ▸    Error reading plugin: heroku-pipelines
 ▸    exit status 1
 ▸    module.js:327
 ▸        throw err;
 ▸        ^
 ▸    
 ▸    Error: Cannot find module 'heroku-pipelines'
 ▸        at Function.Module._resolveFilename (module.js:325:15)
 ▸        at Function.Module._load (module.js:276:25)
 ▸        at Module.require (module.js:353:17)
 ▸        at require (internal/module.js:12:17)
 ▸        at [eval]:2:15
 ▸        at Object.exports.runInThisContext (vm.js:54:17)
 ▸        at Object.<anonymous> ([eval]-wrapper:6:22)
 ▸        at Module._compile (module.js:397:26)
 ▸        at node.js:611:27
 ▸        at nextTickCallbackWith0Args (node.js:452:9)
```

**Comment by timlichen** [comment]
Also having the same issue,
Below are my logs, very similar to @fro 

heroku-cli: Installing core plugins (retrying)...
 ▸    Error reading plugin: heroku-pipelines
 ▸    exit status 1
 ▸    module.js:327
 ▸        throw err;
 ▸        ^
 ▸
 ▸    Error: Cannot find module 'heroku-pipelines'
 ▸        at Function.Module._resolveFilename (module.js:325:15)
 ▸        at Function.Module._load (module.js:276:25)
 ▸        at Module.require (module.js:353:17)
 ▸        at require (internal/module.js:12:17)
 ▸        at [eval]:2:15
 ▸        at Object.exports.runInThisContext (vm.js:54:17)
 ▸        at Object.<anonymous> ([eval]-wrapper:6:22)
 ▸        at Module._compile (module.js:397:26)
 ▸        at node.js:611:27
 ▸        at nextTickCallbackWith0Args (node.js:452:9)
heroku-cli: Installing core plugins (retrying)...
 ▸    Error reading plugin: heroku-pipelines
 ▸    exit status 1
 ▸    module.js:327
 ▸        throw err;
 ▸        ^
 ▸
 ▸    Error: Cannot find module 'heroku-pipelines'
 ▸        at Function.Module._resolveFilename (module.js:325:15)
 ▸        at Function.Module._load (module.js:276:25)
 ▸        at Module.require (module.js:353:17)
 ▸        at require (internal/module.js:12:17)
 ▸        at [eval]:2:15
 ▸        at Object.exports.runInThisContext (vm.js:54:17)
 ▸        at Object.<anonymous> ([eval]-wrapper:6:22)
 ▸        at Module._compile (module.js:397:26)
 ▸        at node.js:611:27
 ▸        at nextTickCallbackWith0Args (node.js:452:9)
 !    error getting commands pid 15450 exit 1
Tims-MBP:Documents timchen$ heroku update
heroku-cli: Installing core plugins (retrying)...
 ▸    Error reading plugin: heroku-pipelines
 ▸    exit status 1
 ▸    module.js:327
 ▸        throw err;
 ▸        ^
 ▸
 ▸    Error: Cannot find module 'heroku-pipelines'
 ▸        at Function.Module._resolveFilename (module.js:325:15)
 ▸        at Function.Module._load (module.js:276:25)
 ▸        at Module.require (module.js:353:17)
 ▸        at require (internal/module.js:12:17)
 ▸        at [eval]:2:15
 ▸        at Object.exports.runInThisContext (vm.js:54:17)
 ▸        at Object.<anonymous> ([eval]-wrapper:6:22)
 ▸        at Module._compile (module.js:397:26)
 ▸        at node.js:611:27
 ▸        at nextTickCallbackWith0Args (node.js:452:9)

**Comment by chrisbloom7** [comment]
Same here after trying two fresh installs:

    rm -rf ~/.heroku
    sudo rm -rf /usr/local/heroku

Download the latest installer from https://toolbelt.heroku.com/ and install it. Open a new terminal window and:

    $ heroku update
    heroku-cli: Installing Toolbelt v4... done
    For more information on Toolbelt v4: https://github.com/heroku/heroku-cli
    heroku-cli: Adding dependencies... done
    heroku-cli: Installing core plugins (retrying)...
     ▸    Error reading plugin: heroku-pipelines
     ▸    exit status 1
     ▸    module.js:327
     ▸        throw err;
     ▸        ^
     ▸    
     ▸    Error: Cannot find module 'heroku-pipelines'
     ▸        at Function.Module._resolveFilename (module.js:325:15)
     ▸        at Function.Module._load (module.js:276:25)
     ▸        at Module.require (module.js:353:17)
     ▸        at require (internal/module.js:12:17)
     ▸        at [eval]:2:15
     ▸        at Object.exports.runInThisContext (vm.js:54:17)
     ▸        at Object.<anonymous> ([eval]-wrapper:6:22)
     ▸        at Module._compile (module.js:397:26)
     ▸        at node.js:611:27
     ▸        at nextTickCallbackWith0Args (node.js:452:9)
    heroku-cli: Installing core plugins (retrying)...
     ▸    Error reading plugin: heroku-pipelines
     ▸    exit status 1
     ▸    module.js:327
     ▸        throw err;
     ▸        ^
     ▸    
     ▸    Error: Cannot find module 'heroku-pipelines'
     ▸        at Function.Module._resolveFilename (module.js:325:15)
     ▸        at Function.Module._load (module.js:276:25)
     ▸        at Module.require (module.js:353:17)
     ▸        at require (internal/module.js:12:17)
     ▸        at [eval]:2:15
     ▸        at Object.exports.runInThisContext (vm.js:54:17)
     ▸        at Object.<anonymous> ([eval]-wrapper:6:22)
     ▸        at Module._compile (module.js:397:26)
     ▸        at node.js:611:27
     ▸        at nextTickCallbackWith0Args (node.js:452:9)
     !    error getting commands pid 4616 exit 1

**Comment by ismith** [comment]
Same.  'npm install -g heroku-pipelines' seems to work fine, though.  I also tried cp'ing the resulting directory (/usr/local/lib/node_modules/heroku-pipelines) to ~/.heroku/node_modules, but running a heroku local command after that emptied ~/.heroku/node_modules and then the same problem (Cannot find module 'heroku-pipelines') occurred.

**Comment by fledman** [comment]
I am also experiencing the same issue. After a fresh install from toolbelt.heroku.com I get:
```
➜  heroku --version
heroku-cli: Installing core plugins (retrying)...
 ▸    Error reading plugin: heroku-pipelines
 ▸    exit status 1
 ▸    module.js:327
 ▸        throw err;
 ▸        ^
 ▸    
 ▸    Error: Cannot find module 'heroku-pipelines'
 ▸        at Function.Module._resolveFilename (module.js:325:15)
 ▸        at Function.Module._load (module.js:276:25)
 ▸        at Module.require (module.js:353:17)
 ▸        at require (internal/module.js:12:17)
 ▸        at [eval]:2:15
 ▸        at Object.exports.runInThisContext (vm.js:54:17)
 ▸        at Object.<anonymous> ([eval]-wrapper:6:22)
 ▸        at Module._compile (module.js:397:26)
 ▸        at node.js:611:27
 ▸        at nextTickCallbackWith0Args (node.js:452:9)
heroku-cli: Installing core plugins (retrying)...
 ▸    Error reading plugin: heroku-pipelines
 ▸    exit status 1
 ▸    module.js:327
 ▸        throw err;
 ▸        ^
 ▸    
 ▸    Error: Cannot find module 'heroku-pipelines'
 ▸        at Function.Module._resolveFilename (module.js:325:15)
 ▸        at Function.Module._load (module.js:276:25)
 ▸        at Module.require (module.js:353:17)
 ▸        at require (internal/module.js:12:17)
 ▸        at [eval]:2:15
 ▸        at Object.exports.runInThisContext (vm.js:54:17)
 ▸        at Object.<anonymous> ([eval]-wrapper:6:22)
 ▸        at Module._compile (module.js:397:26)
 ▸        at node.js:611:27
 ▸        at nextTickCallbackWith0Args (node.js:452:9)
 !    error getting commands pid 60918 exit 1
```

**Comment by sylv3rblade** [comment]
same issue with a new installation from homebrew

sylv3rblade@DevUnit ~/P/p> brew install heroku
==> Downloading https://s3.amazonaws.com/assets.heroku.com/heroku-client/heroku-client-3.42.33.tgz
######################################################################## 100.0%
🍺  /usr/local/Cellar/heroku-toolbelt/3.42.33: 988 files, 6.1M, built in 7 seconds
sylv3rblade@DevUnit ~/P/p> heroku
heroku-cli: Installing core plugins (retrying)...
 ▸    Error reading plugin: heroku-pipelines
 ▸    exit status 1
 ▸    module.js:327
 ▸        throw err;
 ▸        ^
 ▸
 ▸    Error: Cannot find module 'heroku-pipelines'
 ▸        at Function.Module._resolveFilename (module.js:325:15)
 ▸        at Function.Module._load (module.js:276:25)
 ▸        at Module.require (module.js:353:17)
 ▸        at require (internal/module.js:12:17)
 ▸        at [eval]:2:15
 ▸        at Object.exports.runInThisContext (vm.js:54:17)
 ▸        at Object.<anonymous> ([eval]-wrapper:6:22)
 ▸        at Module._compile (module.js:397:26)
 ▸        at node.js:611:27
 ▸        at nextTickCallbackWith0Args (node.js:452:9)
heroku-cli: Installing core plugins (retrying)...
 ▸    Error reading plugin: heroku-pipelines
 ▸    exit status 1
 ▸    module.js:327
 ▸        throw err;
 ▸        ^
 ▸
 ▸    Error: Cannot find module 'heroku-pipelines'
 ▸        at Function.Module._resolveFilename (module.js:325:15)
 ▸        at Function.Module._load (module.js:276:25)
 ▸        at Module.require (module.js:353:17)
 ▸        at require (internal/module.js:12:17)
 ▸        at [eval]:2:15
 ▸        at Object.exports.runInThisContext (vm.js:54:17)
 ▸        at Object.<anonymous> ([eval]-wrapper:6:22)
 ▸        at Module._compile (module.js:397:26)
 ▸        at node.js:611:27
 ▸        at nextTickCallbackWith0Args (node.js:452:9)
 !    error getting commands pid 3327 exit 1

**Comment by TheNaoX** [comment]
I'm experiencing the same issue :(

**Comment by timlichen** [comment]
Looks like the issue is resolved on my end.

**Comment by ismith** [comment]
Like @timlichen, seems to be working now for me.

**Comment by bryceroney** [comment]
Can also confirm appears to be working.

**Comment by fledman** [comment]
seems to be fine now

**Comment by bfollekHOD** [comment]
@ransombriggs - Still not working for me. No proxy, no ~/.npmrc file.

**Comment by chrisbloom7** [comment]
Confirmed working for me

**Comment by fro** [comment]
Working, great.

```
fro@host project (master) $ heroku --version
heroku-cli: Installing core plugins... done
heroku-gem/3.31.3 (x86_64-darwin14.1.0) ruby/1.9.3
heroku-cli/4.27.21-839acbb (amd64-darwin) go1.5.3
=== Installed Plugins
heroku-apps@1.2.4
heroku-cli-addons@0.2.0
heroku-fork@4.1.1
heroku-git@2.4.5
heroku-local@4.1.7
heroku-pipelines@1.0.2
heroku-run@2.9.2
heroku-spaces@2.0.13
heroku-status@2.1.0

WARNING: Toolbelt v3.42.36 update available.
```

**Comment by ransombriggs** [comment]
@fro @sylv3rblade @TheNaoX - Yesterday a revision of access control for Heroku CLI updates caused an unexpected permission failure in the Heroku CLI plugin repository. This failure propagated throughout the CDN we use to publish Heroku CLI plugins. Our engineers have reverted the change and invalidated the faulty data from our CDN.  If you continue to see issues with the Heroku CLI install please try running the `heroku update` command. If it continues to fail after that please let me know.

**Comment by ransombriggs** [comment]
@bfollekHOD - I think your issue might be different than what the other people experienced, but just to eliminate the possibility, could you run `heroku update` and let me know if it succeeds?  Do you have any special firewall settings that are not allowing outbound connections?

**Comment by fro** [comment]
@ransombriggs Thank you for the feedback.

**Comment by bfollekHOD** [comment]
Fixed. It was a firewall issue. I must have inadvertently blocked node. Thanks for your help.
